CREATE TABLE Flight (
    FL_ID VARCHAR2(10) PRIMARY KEY,
    SOURCE VARCHAR2(100),
    DESTINATION VARCHAR2(100),
    ARR_TIME TIMESTAMP,
    DEP_TIME TIMESTAMP,
    AL_ID VARCHAR2(10),
    FOREIGN KEY (AL_ID) REFERENCES Airline(AL_ID)
);
