CREATE TABLE Passenger (
    ID VARCHAR2(10),
    PASSPORT_NO VARCHAR2(20),
    F_NAME VARCHAR2(50),
    M_NAME VARCHAR2(50),
    L_NAME VARCHAR2(50),
    DOB DATE,
    PHONE VARCHAR2(15),
    SEX CHAR(1),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PRIMARY KEY (ID, PASSPORT_NO)
);
