CREATE TABLE TICKET_DETAILS (
    DATE_OF_BOOKING DATE NOT NULL, 
    SOURCE VARCHAR(3) NOT NULL, 
    DESTINATION VARCHAR(3) NOT NULL, 
    CLASS VARCHAR2(15) NOT NULL 
        CONSTRAINT CHK_TICKET_CLASS 
        CHECK (CLASS IN ('ECONOMY', 'BUSINESS', 'FIRST', 'PREMIUM ECONOMY')),
    PRICE INT, 
    PRIMARY KEY(DATE_OF_BOOKING, SOURCE, DESTINATION, CLASS)
);